### ISSUE TITLE
Special characters in Redmine issue description cause exceptions

### ISSUE THREAD

**Issue by andymstone** [tentwentyfour/remaim#19]
If various special characters are present in the description field in a Redmine issue an exception occurs when attempting to transfer to maniphest.  

E.g. I had a description that included the text 'Improve to + - precision' which caused:
```
Exception message: ERR-CONDUIT-CORE: Query has an invalid sequence of operators ("+-").
Exception trace:
#0 /home/phd/libphutil/src/future/FutureProxy.php(58): ConduitFuture->didReceiveResult(Array)
#1 /home/phd/libphutil/src/future/FutureProxy.php(35): FutureProxy->getResult()
#2 /home/phd/libphutil/src/conduit/ConduitClient.php(64): FutureProxy->resolve()
#3 /home/phd/remaim/src/Traits/Phabricator.php(240): ConduitClient->callMethodSynchronous('maniphest.query', Array)
#4 /home/phd/remaim/src/Wizard.php(509): Ttf\Remaim\Wizard->findExistingTask(Array, 'PHID-PROJ-shjug...')
#5 /home/phd/remaim/src/Wizard.php(485): Ttf\Remaim\Wizard->createManiphestTask(Array, false, 'PHID-PROJ-shjug...', Array)
#6 [internal function]: Ttf\Remaim\Wizard->Ttf\Remaim\{closure}(Array)
#7 /home/phd/remaim/src/Wizard.php(486): array_map(Object(Closure), Array)
#8 /home/phd/remaim/src/Wizard.php(100): Ttf\Remaim\Wizard->migrateIssues(Array, Array, Array)
#9 /home/phd/remaim/bin/remaim(48): Ttf\Remaim\Wizard->run()
#10 {main}
```

Also having mismatched double quotes in the description cause a similar problem (slightly different exception) but I assume the solution is the same - correctly escaping the text at some point in remaim.

**Comment by kwisatz** [comment]
Hi @andymstone,

thanks for reporting this and for providing an example. May I ask whether you used the master branch or any of the tags? We have a 0.2.0 version in the works (which has major changes) and I'll see if I can't release this over the weekend, including some escaping of the description texts.

**Comment by kwisatz** [comment]
@andymstone I have just pushed [0.3.0](https://github.com/tentwentyfour/remaim/tree/0.3.0). Can you test if this solves the "Invalid sequence of operators" issue that you described above?

**Comment by andymstone** [comment]
Looks to be working now thanks.

**Comment by kwisatz** [comment]
You're welcome.
